apiVersion: v1
kind: ConfigMap
metadata:
  name: chef-qwen-config
  namespace: qchef
data:
  FRONTEND_URL: "https://qchef.udhomelab.dpdns.org"
  GOOGLE_REDIRECT_URI: "https://qchef.udhomelab.dpdns.org/api/auth/google/callback"
